
#echo "ALTERA_QUARTUS_HOME     = $ALTERA_QUARTUS_HOME"
#echo "ALTERAOCLSDKROOT        = $ALTERAOCLSDKROOT"
#echo "AOCL_BOARD_PACKAGE_ROOT = $AOCL_BOARD_PACKAGE_ROOT"

#export ALTERA_VERSION_PATH=/curr/software/Altera/15.1/
export ALTERA_VERSION_PATH=$ALTERA_QUARTUS_HOME
export QUARTUS_ROOTDIR=$ALTERA_VERSION_PATH/quartus
#export LD_LIBRARY_PATH=$QUARTUS_ROOTDIR/linux64:${LD_LIBRARY_PATH}
#export PATH=$ALTERA_VERSION_PATH/quartus/bin/:$PATH

#export ALTERAOCLSDKROOT=$ALTERA_VERSION_PATH/hld
export PATH=$QUARTUS_ROOTDIR/../qsys/bin/:$PATH
export PATH=$ALTERAOCLSDKROOT/bin/:$PATH
export PATH=$ALTERAOCLSDKROOT/linux64/bin/:$PATH
export LD_LIBRARY_PATH=$ALTERAOCLSDKROOT/linux64/lib:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH=$ALTERAOCLSDKROOT/host/lin64/lib:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH=$ALTERAOCLSDKROOT/host/linux64/lib:${LD_LIBRARY_PATH}
#export AOCL_BOARD_PACKAGE_ROOT=$ALTERA_VERSION_PATH/hld/board/terasic/de5net
export LD_LIBRARY_PATH=$AOCL_BOARD_PACKAGE_ROOT/linux64/lib:${LD_LIBRARY_PATH}
export ACL_PROFILE_TIMER=1
